# Generated by Django 3.2.7 on 2021-09-22 01:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('emoji', models.CharField(max_length=50)),
                ('img_profile', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
